databases:
  - name: gestionflottedb
    plan: free
    databaseName: gestionflotte
    user: gestionflotte

services:
  - type: web
    plan: free
    name: gestionflotte
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn gestion_vehicules.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gestionflottedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 0
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: PYTHON_VERSION
        value: 3.9.9 