# Generated by Django 4.2.20 on 2025-05-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='date_immatriculation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
