# Generated by Django 4.2.20 on 2025-05-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vehicule_date_immatriculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_souhaitee',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
