# Generated by Django 4.2.20 on 2025-05-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='kilometrage',
            field=models.PositiveIntegerField(default=0, help_text="Kilométrage du véhicule au moment de l'entretien"),
        ),
    ]
