# Generated by Django 4.2.20 on 2025-05-14 06:43

from django.db import migrations, models
import entretien.models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0002_entretien_kilometrage'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='piece_justificative',
            field=models.FileField(blank=True, help_text='Facture, reçu ou autre document justificatif (PDF, JPG, PNG)', null=True, upload_to=entretien.models.piece_justificative_path),
        ),
    ]
