# Generated by Django 4.2.10 on 2025-05-10 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckListSecurite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_check', models.CharField(choices=[('depart', 'Départ'), ('retour', 'Retour')], max_length=10)),
                ('date_check', models.DateTimeField(auto_now_add=True)),
                ('parebrise_avant', models.BooleanField(default=False)),
                ('parebrise_arriere', models.BooleanField(default=False)),
                ('retroviseur_gauche', models.BooleanField(default=False)),
                ('retroviseur_droit', models.BooleanField(default=False)),
                ('clignotant', models.BooleanField(default=False)),
                ('feu_arriere_gauche', models.BooleanField(default=False)),
                ('feu_arriere_droit', models.BooleanField(default=False)),
                ('feu_position_gauche', models.BooleanField(default=False)),
                ('feu_position_droit', models.BooleanField(default=False)),
                ('kilometrage', models.PositiveIntegerField()),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('agent_securite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_lists_effectuees', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_lists', to='core.vehicule')),
            ],
        ),
    ]
