# Generated by Django 4.2.20 on 2025-05-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securite', '0002_update_checklistsecurite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistsecurite',
            options={},
        ),
        migrations.RenameField(
            model_name='checklistsecurite',
            old_name='observations',
            new_name='commentaires',
        ),
        migrations.RemoveField(
            model_name='checklistsecurite',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='checklistsecurite',
            name='gilet',
        ),
    ]
