# Generated by Django 4.2.20 on 2025-05-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securite', '0003_add_commentaires_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistsecurite',
            name='logos',
            field=models.CharField(choices=[('present', 'Présents'), ('absent', 'Absents')], default='present', max_length=20),
        ),
    ]
