# Generated by Django 4.2.20 on 2025-05-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securite', '0004_add_logos_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistsecurite',
            name='type_check',
            field=models.CharField(choices=[('depart', 'Avant course'), ('retour', 'Après course')], default='depart', max_length=10, verbose_name='Type de check-list'),
        ),
    ]
