# Generated by Django 4.2.10 on 2025-05-10 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance_parcourue', models.PositiveIntegerField(default=0)),
                ('nombre_courses', models.PositiveIntegerField(default=0)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='core.vehicule')),
            ],
            options={
                'unique_together': {('vehicule', 'date')},
            },
        ),
    ]
