# Generated by Django 4.2.20 on 2025-05-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivivehicule',
            name='date_immatriculation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suivivehicule',
            name='distance_totale',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suivivehicule',
            name='nombre_entretiens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suivivehicule',
            name='volume_carburant_consomme',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
