# Generated by Django 4.2.10 on 2025-05-10 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ravitaillement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ravitaillement', models.DateTimeField(auto_now_add=True)),
                ('kilometrage_avant', models.PositiveIntegerField()),
                ('kilometrage_apres', models.PositiveIntegerField()),
                ('litres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cout_unitaire', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cout_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ravitaillements_crees', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ravitaillements', to='core.vehicule')),
            ],
        ),
    ]
