# Generated by Django 4.2.20 on 2025-05-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravitaillement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ravitaillement',
            name='cout_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ravitaillement',
            name='cout_unitaire',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ravitaillement',
            name='kilometrage_apres',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ravitaillement',
            name='kilometrage_avant',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ravitaillement',
            name='litres',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
