# Generated by Django 4.2.20 on 2025-05-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravitaillement', '0002_alter_ravitaillement_cout_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ravitaillement',
            name='nom_station',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de la station'),
        ),
    ]
