# Generated by Django 4.2.20 on 2025-05-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravitaillement', '0003_ravitaillement_nom_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='ravitaillement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_ravitaillements/', verbose_name='Photo du reçu'),
        ),
    ]
