# Generated by Django 4.2.20 on 2025-05-12 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_enabled', models.BooleanField(default=True, verbose_name='Notifications SMS')),
                ('whatsapp_enabled', models.BooleanField(default=True, verbose_name='Notifications WhatsApp')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Notifications Email')),
                ('notif_demande_course', models.BooleanField(default=True, verbose_name='Demandes de course')),
                ('notif_validation_course', models.BooleanField(default=True, verbose_name='Validation de course')),
                ('notif_expiration_docs', models.BooleanField(default=True, verbose_name='Expiration de documents')),
                ('notif_entretien', models.BooleanField(default=True, verbose_name='Entretiens programmés')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('app', 'Application')], max_length=10)),
                ('titre', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('delivered', 'Livré'), ('failed', 'Échec')], default='pending', max_length=10)),
                ('erreur', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.course')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recues', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.vehicule')),
            ],
        ),
    ]
